### ISSUE TITLE
Cannot force 4k

### ISSUE THREAD

**Issue by priyadarshan** [omniosorg/kayak#72]
Installing OmniOS on NVMe Samsung 960 Pro, having set `Force 4K Sectors` to `YES`, OmniOS installer signals:

```
Cannot unload module: sd
Will be unloaded upon reboot.
Forcing update of sd.conf.
failed to read label from /dev/dsk/c4t0025385971B16535d0s0
```

![screenshot 2018-09-04 at 09 47 57](https://user-images.githubusercontent.com/1652143/45017626-5c636b80-b028-11e8-8666-28aa7f833a54.png)

Checking post-install, ashift is indeed 9.

Unfortunately I realised this after doing many installs.

The error message is flashing too quickly to recognise and it did not come to me to double check until now.

By the way, many SSD, including Samsung 950, 960, 970 are 8K drives, it seems they should have ashift=13.

It would be nice to have option to force either 4K or 8K.

Thank you.

**Comment by citrus-it** [comment]
Can you post the contents of `/kernel/drv/sd.conf` on the installed system?
My guess would be that we need to do this a different way for NVMe.

**Comment by citrus-it** [comment]
Can you try dropping to the shell in the installer before starting installation, and typing:

```
echo "min-phys-block-size=4096;" >> /kernel/drv/nvme.conf
update_drv -f nvme
exit
```

Then do the installation and see if you get ashift=12?
(or try 8192 for ashift=13)

**Comment by priyadarshan** [comment]
> Can you post the contents of /kernel/drv/sd.conf on the installed system?

```
root@omnis:~# cat /kernel/drv/sd.conf
#
# CDDL HEADER START
#
# The contents of this file are subject to the terms of the
# Common Development and Distribution License (the "License").
# You may not use this file except in compliance with the License.
#
# You can obtain a copy of the license at usr/src/OPENSOLARIS.LICENSE
# or http://www.opensolaris.org/os/licensing.
# See the License for the specific language governing permissions
# and limitations under the License.
#
# When distributing Covered Code, include this CDDL HEADER in each
# file and include the License file at usr/src/OPENSOLARIS.LICENSE.
# If applicable, add the following below this CDDL HEADER, with the
# fields enclosed by brackets "[]" replaced with your own identifying
# information: Portions Copyright [yyyy] [name of copyright owner]
#
# CDDL HEADER END
#

#
# Copyright (c) 1991, 2010, Oracle and/or its affiliates. All rights reserved.
#

name="sd" class="scsi" target=0 lun=0;
name="sd" class="scsi" target=1 lun=0;
name="sd" class="scsi" target=2 lun=0;
name="sd" class="scsi" target=3 lun=0;
name="sd" class="scsi" target=4 lun=0;
name="sd" class="scsi" target=5 lun=0;
name="sd" class="scsi" target=6 lun=0;
name="sd" class="scsi" target=7 lun=0;
name="sd" class="scsi" target=8 lun=0;
name="sd" class="scsi" target=9 lun=0;
name="sd" class="scsi" target=10 lun=0;
name="sd" class="scsi" target=11 lun=0;
name="sd" class="scsi" target=12 lun=0;
name="sd" class="scsi" target=13 lun=0;
name="sd" class="scsi" target=14 lun=0;
name="sd" class="scsi" target=15 lun=0;

#
# The following stub node is needed for pathological bottom-up
# devid resolution on a self-identifying transport.
#
name="sd" class="scsi-self-identifying";

#
# Associate the driver with devid resolution.
#
ddi-devid-registrant=1;
```

**Comment by priyadarshan** [comment]
> Can you try dropping to the shell in the installer before starting installation, and typing:
It fails with an error that flashes through the screen. I am now taking a video so I can read it and post it here.

**Comment by priyadarshan** [comment]
I tried twice, just in case, but ashift is still 9:

```
root@omniosce:~# zdb
rpool:
    version: 5000
    name: 'rpool'
    state: 0
    txg: 131
    pool_guid: 1357762110761258899
    hostid: 146670196
    hostname: 'omniosce'
    com.delphix:has_per_vdev_zaps
    vdev_children: 1
    vdev_tree:
        type: 'root'
        id: 0
        guid: 1357762110761258899
        create_txg: 4
        children[0]:
            type: 'disk'
            id: 0
            guid: 17958557208562143769
            path: '/dev/dsk/c4t0025385971B16535d0s1'
            devid: 'id1,kdev@w0025385971b16535/b'
            phys_path: '/pci@37,0/pci1022,1453@1,1/pci144d,a801@0/blkdev@w0025385971B16535,0:b'
            whole_disk: 1
            metaslab_array: 38
            metaslab_shift: 32
            ashift: 9
            asize: 511828295680
            is_log: 0
            create_txg: 4
            com.delphix:vdev_zap_leaf: 36
            com.delphix:vdev_zap_top: 37
    features_for_read:
        com.delphix:hole_birth
        com.delphix:embedded_data
```

This is the screenshot, taken after the suggested edit. I did `cat /kernel/drv/nvme.conf` to show file content after edit. I am not sure if that message is good or not.

![00004014](https://user-images.githubusercontent.com/1652143/45031722-e8d55480-b04f-11e8-80e6-6c676660824b.JPG)

**Comment by citrus-it** [comment]
Could you give https://downloads.omniosce.org/media/bloody/omniosce-bloody-20180905.iso a spin please?
This one allows selection of 4K or 8K as well as leaving it to whatever the disk advertises.

**Comment by priyadarshan** [comment]
Do you happen to have a usb version? I am struggling to "burn" iso to thumbdrive (using either unetbooting or rufus vis vmware)

**Comment by citrus-it** [comment]
https://downloads.omniosce.org/media/bloody/omniosce-bloody-20180905.usb-dd

**Comment by priyadarshan** [comment]
Thank you, `usb-dd` version imaged with no issues.

I installed it twice, to test both 4K and 8K.

Ashift values now are set-up as `ashift=12` and `ashift=13` respectively.

```
priyadarshan@omniosce:~$ uname -a
SunOS omniosce 5.11 omnios-master-36eb49126f i86pc i386 i86pc
```

First as 4K, to a Samsung 960 Pro 512GB:

```
priyadarshan@omniosce:~$ zdb
rpool:
    version: 5000
    name: 'rpool'
    state: 0
    txg: 106
    pool_guid: 2254942589280409017
    hostid: 146670196
    hostname: ''
    com.delphix:has_per_vdev_zaps
    vdev_children: 1
    vdev_tree:
        type: 'root'
        id: 0
        guid: 2254942589280409017
        create_txg: 4
        children[0]:
            type: 'disk'
            id: 0
            guid: 14092311627064017026
            path: '/dev/dsk/c4t0025385971B16535d0s1'
            devid: 'id1,kdev@w0025385971b16535/b'
            phys_path: '/pci@38,0/pci1022,1453@1,1/pci144d,a801@0/blkdev@w0025385971B16535,0:b'
            whole_disk: 1
            metaslab_array: 38
            metaslab_shift: 32
            ashift: 12
            asize: 511828295680
            is_log: 0
            create_txg: 4
            com.delphix:vdev_zap_leaf: 36
            com.delphix:vdev_zap_top: 37
    features_for_read:
        com.delphix:hole_birth
        com.delphix:embedded_data
```

Then as 8K, to a Samsung 960 Pro 1TB:

```
store@omniosce8k:~$ zdb
rpool:
    version: 5000
    name: 'rpool'
    state: 0
    txg: 128
    pool_guid: 397576901342805206
    hostid: 146670196
    hostname: 'omniosce8k'
    com.delphix:has_per_vdev_zaps
    vdev_children: 1
    vdev_tree:
        type: 'root'
        id: 0
        guid: 397576901342805206
        create_txg: 4
        children[0]:
            type: 'disk'
            id: 0
            guid: 17656612001213952747
            path: '/dev/dsk/c5t0025385181B144D5d0s1'
            devid: 'id1,kdev@w0025385181b144d5/b'
            phys_path: '/pci@38,0/pci1022,1453@1,2/pci144d,a801@0/blkdev@w0025385181B144D5,0:b'
            whole_disk: 1
            metaslab_array: 38
            metaslab_shift: 33
            ashift: 13
            asize: 1023927648256
            is_log: 0
            create_txg: 4
            com.delphix:vdev_zap_leaf: 36
            com.delphix:vdev_zap_top: 37
    features_for_read:
        com.delphix:hole_birth
        com.delphix:embedded_data
```

One small thing I noticed, in the first case I let `hostname` at default value "omniosce", but zdb reports empty filed, while second time I specified hostname "omniosce8k", and zdb reports `hostname: 'omniosce8k'`.

This is excellent, thank you so much!
